crds:
  # Install and upgrade CRDs. default is true
  install: true
  # Keep CRDs on chart uninstall. default is false
  keep: false


redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2